# Generated by Django 5.1.2 on 2024-10-26 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_alter_wishlist_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to='wishlist.category'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
