# Generated by Django 5.1.2 on 2024-10-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuplanning', '0008_chosenmenu_save_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chosenmenu',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
