# Generated by Django 5.1.2 on 2024-10-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuplanning', '0009_alter_cartitem_quantity_alter_chosenmenu_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenmenu',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
