# Generated by Django 5.1.2 on 2024-10-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userdashboard_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboard',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdashboard',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
