# Generated by Django 5.1.1 on 2024-10-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warung', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('gambar', models.CharField(max_length=100)),
            ],
        ),
    ]
